### ISSUE TITLE
Unable to connect to the database from Java Spring application

### ISSUE THREAD

**Issue by Gyrf921** [railwayapp-templates/postgres-ssl#8]
To use postgres and spring, you need to use `jdbc:postgresql:/${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:postgres}`
The recently submitted link is loaded from `postgres://postgres:...`
Because of this (or because of other problems), try replacing the serum with the one you need for spring and connect to the subsequent setup

```
datasource:
    url: jdbc:postgresql:/${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:postgres}
    password: ${PGPASSWORD:1234}
    username: ${PGUSER:postgres}
    driver-class-name: org.postgresql.Driver
```

it outputs the following information:
```
Failed to get a connection to the request metadata
java.lang.RuntimeException: The org.postgresql.Driver driver claims that it does not accept the jdbc Url, jdbc:postgresql:/viaduct.proxy.rlwy.net:43869/railway
```
